#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

RUNTIME_CONFIG=/var/run/lantally-agent.json

start_service() {
	local enabled server_url site_id node_id token_file interval iface

	config_load lantally
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0
	config_get server_url main server_url
	config_get site_id main site_id
	config_get node_id main node_id
	config_get token_file main token_file
	config_get interval main interval 15s
	config_get_bool iface main iface 1

	. /usr/share/libubox/jshn.sh
	json_init
	json_add_string server_url "$server_url"
	json_add_string site_id "$site_id"
	json_add_string node_id "$node_id"
	json_add_string token_file "$token_file"
	json_add_string interval "$interval"
	json_add_object collectors
	json_add_boolean iface "$iface"
	json_close_object
	umask 077
	json_dump >"$RUNTIME_CONFIG"

	procd_open_instance
	procd_set_param command /usr/bin/lantally-agent -config "$RUNTIME_CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/lantally "$token_file"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger lantally
}
